### ISSUE TITLE
alguma ajuda

### ISSUE THREAD

**Issue by luizpizano** [PauloAguiar/ces27-lab1#8]
comentarios da funcao de reduce ensinam sobre map, quando na verdade trabalhamos com a struct

imagem do github para ilustrar reduce não dá a entender que o array de struct pode ter duas entradas com a mesma chave

no teste do reduce, + tem que ser considerado 1

"A saída de ambas as funções é uma estrutura do tipo map[string]string.", mas na verdade é do tipo mapreduce.KeyValue

comentar que cast string() num int não é o que deve ser feito, mas sim a conversão strconv.Itoa, poupa tempo de pembas como eu; já o cast string() no tipo byte é suficiente

comentario da funcao split sugere mapFileName para nome de arquivo, mas ela nao deve ser usada para o "test_data"

**Comment by PauloAguiar** [comment]
Acho que todos os pontos foram resolvidos na última versão.
